- hosts: centos
  become: yes
  tasks:
  - name: Install mariadb server
    yum:
      name: mariadb-server
      state: latest
    tags:
    - install
    - all
  - name: start mariadb
    service:
      name: mariadb
      state: started
    tags:
    - start
    - all
