- hosts: linux
  tasks:
  - name: execute echo cmd
    debug: msg=" ansible {{ item[0] }} on day {{ item[1] }} is {{ item[2] }}"
    with_nested:
    - [ training, lab, handson ]
    - [ 1, 2, 3 ]
    - [ good, bad, great ]

